# Generated by Django 4.0.2 on 2022-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=20)),
                ('stuemail', models.CharField(max_length=30)),
                ('stupass', models.CharField(max_length=20)),
            ],
        ),
    ]
